"""Stages 3-4: fee generated by a candle, and how it spreads across bins."""

from config import FEE_RATE, POOL_SHARE


def candle_fee(volume_usd: float, pool_share: float, fee_rate: float) -> float:
    """USD fees the pool earns from one candle.

    Of the candle's total market volume, this pool routes `pool_share`,
    and charges `fee_rate` on what it routes.
    """
    pool_volume = volume_usd * pool_share
    return pool_volume * fee_rate


def distribute_fee(fee: float, touched_bins: list[int]) -> dict[int, float]:
    """Split one candle's fee among the bins the candle touched.

    v1: equal split — every touched bin gets fee / len(touched_bins).
    Deliberately its own function: a weighted split can replace it later
    without touching anything else.
    """
    share = fee / len(touched_bins)
    return {bin_id: share for bin_id in touched_bins}


def accumulate_bin_fees(df):
    """Distribute every candle's fee to its touched bins.

    Expects a dataframe with volume_usd and touched_bins columns
    (i.e. the output of candle_bins.add_bins_to_dataframe).

    Returns:
        total_bin_fees: dict bin_id -> total USD fees over the whole df
        per_candle_bin_fees: list, one dict per candle (same order as df
            rows), each the distribute_fee output for that candle
    """
    total_bin_fees = {}
    per_candle_bin_fees = []
    for volume, bins in zip(df["volume_usd"], df["touched_bins"]):
        fee = candle_fee(volume, POOL_SHARE, FEE_RATE)
        split = distribute_fee(fee, bins)

        # Conservation: the split must hand out exactly the fee that came in.
        assert abs(sum(split.values()) - fee) < 1e-9

        per_candle_bin_fees.append(split)
        for bin_id, share in split.items():
            total_bin_fees[bin_id] = total_bin_fees.get(bin_id, 0.0) + share
    return total_bin_fees, per_candle_bin_fees


if __name__ == "__main__":
    # Reference example: $100M volume, 2% share, 0.1% fee -> exactly $2,000.
    assert candle_fee(100_000_000, 0.02, 0.001) == 2_000.0
    print("reference example passes: $100M volume -> $2,000 fee")

    # --- distribute_fee ----------------------------------------------------
    split = distribute_fee(6.0, [-1288, -1287, -1286])
    print("$6 over 3 bins ->", split)
    assert split == {-1288: 2.0, -1287: 2.0, -1286: 2.0}

    split = distribute_fee(5.0, [-1287])
    print("$5 over 1 bin  ->", split)
    assert split == {-1287: 5.0}

    # Conservation: what goes in must come out, even when the equal share
    # is a non-terminating decimal like 10/3.
    split = distribute_fee(10.0, [-1288, -1287, -1286])
    assert abs(sum(split.values()) - 10.0) < 1e-9
    print("conservation holds: $10 over 3 bins sums back to "
          f"{sum(split.values()):.12f}")

    import pandas as pd

    df = pd.read_csv("data/sol_1m.csv")
    fees = df["volume_usd"].map(lambda v: candle_fee(v, POOL_SHARE, FEE_RATE))
    days = len(df) / 1440  # 1440 one-minute candles per day

    print(f"\ncandles: {len(df)} ({days:.1f} days)")
    print(f"total market volume: ${df['volume_usd'].sum():,.0f}")
    print(f"total pool fees:     ${fees.sum():,.2f}")
    print(f"avg fee per candle:  ${fees.mean():,.4f}")
    print(f"fee per day:         ${fees.sum() / days:,.2f}")

    # --- Toy example: 3 candles around bin X --------------------------------
    # Fees $3 / $2 / $1 via volumes chosen so candle_fee gives those numbers.
    # Hand calculation:
    #   candle 1: $3 over {X, X+1, X+2} -> $1 each
    #   candle 2: $2 over {X+1, X+2}    -> $1 each
    #   candle 3: $1 over {X+1}         -> $1
    #   totals:   X: $1,  X+1: $3,  X+2: $2
    X = -1287
    toy = pd.DataFrame({
        "volume_usd": [150_000, 100_000, 50_000],  # -> fees $3, $2, $1
        "touched_bins": [[X, X + 1, X + 2], [X + 1, X + 2], [X + 1]],
    })
    toy_totals, toy_per_candle = accumulate_bin_fees(toy)
    print("\n--- toy example ---")
    for i, split in enumerate(toy_per_candle):
        print(f"candle {i + 1}: {split}")
    print(f"totals by code: {toy_totals}")
    print(f"totals by hand: {{{X}: 1.0, {X + 1}: 3.0, {X + 2}: 2.0}}")
    for bin_id, expected in {X: 1.0, X + 1: 3.0, X + 2: 2.0}.items():
        assert abs(toy_totals[bin_id] - expected) < 1e-9

    # --- Accumulate over the real CSV --------------------------------------
    from bin_math import get_bin_range
    from candle_bins import BIN_STEP, add_bins_to_dataframe, raw_to_ui

    df = add_bins_to_dataframe(df, BIN_STEP)
    total_bin_fees, per_candle_bin_fees = accumulate_bin_fees(df)

    grand_total = sum(total_bin_fees.values())
    print("\n--- per-bin totals over the whole CSV ---")
    print(f"bins that ever earned a fee: {len(total_bin_fees)}")
    print(f"sum of per-bin totals: ${grand_total:,.2f} "
          f"(candle fees: ${fees.sum():,.2f})")
    assert abs(grand_total - fees.sum()) < 1e-6

    print("top 5 earning bins:")
    for bin_id in sorted(total_bin_fees, key=total_bin_fees.get, reverse=True)[:5]:
        lo, hi = get_bin_range(bin_id, BIN_STEP)
        print(f"  bin {bin_id}: ${total_bin_fees[bin_id]:,.2f}"
              f"  (UI ${raw_to_ui(lo):.2f}-{raw_to_ui(hi):.2f})")

    # --- Bar chart: total fee per bin --------------------------------------
    import matplotlib.pyplot as plt

    bin_ids = sorted(total_bin_fees)
    totals = [total_bin_fees[b] for b in bin_ids]

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.bar(bin_ids, totals, width=0.8, color="#2563eb")
    ax.set_title(
        f"Total fee earned per bin over {days:.0f} days "
        f"(step {BIN_STEP}, equal split)",
        fontsize=11, color="#3f3f46",
    )
    ax.set_xlabel("bin id (raw-price convention)", color="#52525b")
    ax.set_ylabel("total fee (USD)", color="#52525b")
    ax.tick_params(colors="#52525b", labelsize=9)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    fig.tight_layout()
    fig.savefig("data/fee_per_bin.png", dpi=150)
    print("\nchart saved to data/fee_per_bin.png")
