"""Fee generated by a candle, and how it spreads across bins."""

from bin_math import get_bin_range
from candle_bins import ui_to_raw
from config import BIN_STEP, FEE_DISTRIBUTION, FEE_RATE, POOL_SHARE


def candle_fee(volume_usd: float, pool_share: float, fee_rate: float) -> float:
    """USD fees the pool earns from one candle.

    Of the candle's total market volume, this pool routes `pool_share`,
    and charges `fee_rate` on what it routes.
    """
    pool_volume = volume_usd * pool_share
    return pool_volume * fee_rate


def distribute_fee(fee: float, touched_bins: list[int]) -> dict[int, float]:
    """Split one candle's fee among the bins the candle touched.

    Equal split: every touched bin gets fee / len(touched_bins).
    Deliberately its own function: a weighted split can replace it later
    without touching anything else.
    """
    share = fee / len(touched_bins)
    return {bin_id: share for bin_id in touched_bins}


def distribute_fee_weighted(
    fee: float,
    touched_bins: list[int],
    low: float,
    high: float,
    bin_step: int,
) -> dict[int, float]:
    """Split one candle's fee among its bins by price-range overlap.

    low/high are the candle's range in RAW on-chain prices — the same
    convention the bin ids use, so they are comparable with get_bin_range.
    Each bin's weight is the fraction of [low, high] lying inside that
    bin's price range: a bin the price traversed fully gets a large
    share, a bin it barely clipped gets a small one. Weights sum to 1.

    Overlap length is a proxy for traded volume: OHLC data says the price
    visited every point of [low, high] but not how much volume traded at
    each point, so "time spent" and "volume traded" per bin are unknown.

    A zero-length candle (low == high) has no length to weight by; fall
    back to the equal split. Such a candle touches exactly one bin, so
    the result is the whole fee to that bin either way.
    """
    if low == high:
        return distribute_fee(fee, touched_bins)

    overlaps = {}
    for bin_id in touched_bins:
        bin_lo, bin_hi = get_bin_range(bin_id, bin_step)
        overlaps[bin_id] = max(0.0, min(high, bin_hi) - max(low, bin_lo))
    total = sum(overlaps.values())
    # A real candle range that misses its own touched bins means the
    # inputs disagree about units; without this check the split would
    # quietly hand out zeros instead of failing.
    assert total > 0.0, (
        f"candle range [{low}, {high}] has zero overlap with touched bins "
        f"{touched_bins}: low/high are likely in the wrong price units "
        "(they must be RAW on-chain prices, not UI prices)"
    )
    return {bin_id: fee * ov / total for bin_id, ov in overlaps.items()}


def accumulate_bin_fees(df, fee_distribution=None, fee_rate=None):
    """Distribute every candle's fee to its touched bins.

    Expects a dataframe with volume_usd and touched_bins columns
    (i.e. the output of candle_bins.add_bins_to_dataframe); "weighted"
    additionally needs the low/high columns (UI prices, as in the CSV).

    fee_distribution: "equal" or "weighted"; None (the default) means
    use config.FEE_DISTRIBUTION. The parameter exists so both modes can
    be compared in one process without editing the config.

    fee_rate: None (the default) means use config.FEE_RATE. Overriding it
    lets a caller re-run at a different rate in the same process, which is
    how the break-even fee rate is verified.

    Returns:
        total_bin_fees: dict bin_id -> total USD fees over the whole df
        per_candle_bin_fees: list, one dict per candle (same order as df
            rows), each the fee split for that candle
    """
    if fee_distribution is None:
        fee_distribution = FEE_DISTRIBUTION
    if fee_distribution not in ("equal", "weighted"):
        raise ValueError(f"unknown fee_distribution: {fee_distribution!r}")
    if fee_rate is None:
        fee_rate = FEE_RATE
    weighted = fee_distribution == "weighted"
    # Placeholders keep a single loop; the equal path never reads them,
    # so dataframes without low/high columns still work in equal mode.
    lows = df["low"] if weighted else [None] * len(df)
    highs = df["high"] if weighted else [None] * len(df)

    total_bin_fees = {}
    per_candle_bin_fees = []
    for volume, bins, low, high in zip(
            df["volume_usd"], df["touched_bins"], lows, highs):
        fee = candle_fee(volume, POOL_SHARE, fee_rate)
        if weighted:
            split = distribute_fee_weighted(
                fee, bins, ui_to_raw(low), ui_to_raw(high), BIN_STEP)
        else:
            split = distribute_fee(fee, bins)

        # Conservation: the split must hand out exactly the fee that came in.
        assert abs(sum(split.values()) - fee) < 1e-9

        per_candle_bin_fees.append(split)
        for bin_id, share in split.items():
            total_bin_fees[bin_id] = total_bin_fees.get(bin_id, 0.0) + share
    return total_bin_fees, per_candle_bin_fees


if __name__ == "__main__":
    # Reference example: $100M volume, 2% share, 0.1% fee -> exactly $2,000.
    assert candle_fee(100_000_000, 0.02, 0.001) == 2_000.0
    print("reference example passes: $100M volume -> $2,000 fee")

    # --- distribute_fee ----------------------------------------------------
    split = distribute_fee(6.0, [-1288, -1287, -1286])
    print("$6 over 3 bins ->", split)
    assert split == {-1288: 2.0, -1287: 2.0, -1286: 2.0}

    split = distribute_fee(5.0, [-1287])
    print("$5 over 1 bin  ->", split)
    assert split == {-1287: 5.0}

    # Conservation: what goes in must come out, even when the equal share
    # is a non-terminating decimal like 10/3.
    split = distribute_fee(10.0, [-1288, -1287, -1286])
    assert abs(sum(split.values()) - 10.0) < 1e-9
    print("conservation holds: $10 over 3 bins sums back to "
          f"{sum(split.values()):.12f}")

    # --- distribute_fee_weighted -------------------------------------------
    # Single-bin candle: low != high, both strictly inside the same bin
    # (not a doji, not touching either edge). The bin's overlap equals
    # the whole candle range, so its weight is exactly 1.0 and the
    # weighted split must equal the equal split.
    lo, hi = get_bin_range(-1287, BIN_STEP)
    mid = (lo + hi) / 2
    width = hi - lo
    w = distribute_fee_weighted(
        5.0, [-1287], lo + 0.25 * width, lo + 0.75 * width, BIN_STEP)
    assert w == distribute_fee(5.0, [-1287]) == {-1287: 5.0}
    print("\nweighted, single-bin candle (strictly inside) -> weight 1.0, "
          f"identical to equal split: {w}")

    # Zero-length candle (low == high): falls back to the equal split.
    w = distribute_fee_weighted(5.0, [-1287], mid, mid, BIN_STEP)
    assert abs(w[-1287] - 5.0) < 1e-9
    print("weighted, zero-length candle -> equal-split fallback, no crash")

    # Wrong units (UI prices instead of raw) must fail loudly, not
    # silently produce zeros or degrade to the equal split.
    try:
        distribute_fee_weighted(5.0, [-1287], 76.4, 76.6, BIN_STEP)
        raise SystemExit("units guard did NOT fire on UI-price inputs")
    except AssertionError:
        print("weighted, UI prices by mistake -> AssertionError (guard fires)")

    # Two FULL bins: shares follow bin widths. Neighboring bin widths grow
    # by the factor (1 + step/10000), so the upper bin's share must be
    # exactly 1.002x the lower bin's at step 20 — not 50/50.
    a_lo, a_hi = get_bin_range(-1288, BIN_STEP)
    b_lo, b_hi = get_bin_range(-1287, BIN_STEP)
    w = distribute_fee_weighted(10.0, [-1288, -1287], a_lo, b_hi, BIN_STEP)
    ratio = w[-1287] / w[-1288]
    print(f"weighted, two full bins -> shares {w[-1288]:.6f} / {w[-1287]:.6f}, "
          f"upper/lower ratio {ratio:.6f} (bin-width ratio 1.002)")
    assert abs(ratio - 1.002) < 1e-9
    assert abs(sum(w.values()) - 10.0) < 1e-9

    # Half a bin + full bin + quarter bin: conservation and ordering.
    c_lo, c_hi = get_bin_range(-1286, BIN_STEP)
    low = (a_lo + a_hi) / 2            # covers upper half of bin -1288
    high = c_lo + 0.25 * (c_hi - c_lo)  # covers lower quarter of bin -1286
    w = distribute_fee_weighted(6.0, [-1288, -1287, -1286], low, high, BIN_STEP)
    assert abs(sum(w.values()) - 6.0) < 1e-9
    assert w[-1287] > w[-1288] > w[-1286]  # full > half > quarter
    print("weighted, half/full/quarter bins -> "
          + ", ".join(f"{b}: ${s:.4f}" for b, s in w.items())
          + f" (sum {sum(w.values()):.10f})")

    import pandas as pd

    from data_io import load_candles

    df = load_candles()
    fees = df["volume_usd"].map(lambda v: candle_fee(v, POOL_SHARE, FEE_RATE))
    days = len(df) / 1440  # 1440 one-minute candles per day

    print(f"\ncandles: {len(df)} ({days:.1f} days)")
    print(f"total market volume: ${df['volume_usd'].sum():,.0f}")
    print(f"total pool fees:     ${fees.sum():,.2f}")
    print(f"avg fee per candle:  ${fees.mean():,.4f}")
    print(f"fee per day:         ${fees.sum() / days:,.2f}")

    # --- Toy example: 3 candles around bin X --------------------------------
    # Fees $3 / $2 / $1 via volumes chosen so candle_fee gives those numbers.
    # Hand calculation:
    #   candle 1: $3 over {X, X+1, X+2} -> $1 each
    #   candle 2: $2 over {X+1, X+2}    -> $1 each
    #   candle 3: $1 over {X+1}         -> $1
    #   totals:   X: $1,  X+1: $3,  X+2: $2
    X = -1287
    toy = pd.DataFrame({
        "volume_usd": [150_000, 100_000, 50_000],  # -> fees $3, $2, $1
        "touched_bins": [[X, X + 1, X + 2], [X + 1, X + 2], [X + 1]],
    })
    toy_totals, toy_per_candle = accumulate_bin_fees(toy)
    print("\n--- toy example ---")
    for i, split in enumerate(toy_per_candle):
        print(f"candle {i + 1}: {split}")
    print(f"totals by code: {toy_totals}")
    print(f"totals by hand: {{{X}: 1.0, {X + 1}: 3.0, {X + 2}: 2.0}}")
    for bin_id, expected in {X: 1.0, X + 1: 3.0, X + 2: 2.0}.items():
        assert abs(toy_totals[bin_id] - expected) < 1e-9

    # --- Accumulate over the real CSV --------------------------------------
    from candle_bins import add_bins_to_dataframe, raw_to_ui

    df = add_bins_to_dataframe(df, BIN_STEP)

    # --- Hand-check the weighted split on one real multi-bin candle --------
    row = df[df["num_bins"] >= 3].iloc[0]
    c_low, c_high = ui_to_raw(row["low"]), ui_to_raw(row["high"])
    c_fee = candle_fee(row["volume_usd"], POOL_SHARE, FEE_RATE)
    w = distribute_fee_weighted(c_fee, row["touched_bins"], c_low, c_high, BIN_STEP)

    print(f"\n--- weighted hand-check: candle at {row['timestamp']} ---")
    print(f"low  = {row['low']:.6f} UI = {c_low:.9f} raw")
    print(f"high = {row['high']:.6f} UI = {c_high:.9f} raw")
    print(f"candle range length = {c_high - c_low:.9f} raw")
    print(f"candle fee = ${c_fee:.4f}  (volume ${row['volume_usd']:,.0f})")
    total_overlap = 0.0
    for b in row["touched_bins"]:
        b_lo, b_hi = get_bin_range(b, BIN_STEP)
        ov = max(0.0, min(c_high, b_hi) - max(c_low, b_lo))
        total_overlap += ov
        print(f"  bin {b}: raw [{b_lo:.9f}, {b_hi:.9f})"
              f"  overlap {ov:.9f}  weight {ov / (c_high - c_low):7.4%}"
              f"  fee ${w[b]:.4f}")
    assert abs(total_overlap - (c_high - c_low)) < 1e-12  # bins tile the range
    assert abs(sum(w.values()) - c_fee) < 1e-9            # conservation
    equal_split = distribute_fee(c_fee, row["touched_bins"])
    print(f"  sum of weights = {total_overlap / (c_high - c_low):.10f}")
    print(f"  sum of weighted fees = ${sum(w.values()):.4f} (candle fee ${c_fee:.4f})")
    print(f"  equal split for comparison: "
          + ", ".join(f"{b}: ${s:.4f}" for b, s in equal_split.items()))
    total_bin_fees, per_candle_bin_fees = accumulate_bin_fees(df)

    grand_total = sum(total_bin_fees.values())
    print("\n--- per-bin totals over the whole CSV ---")
    print(f"bins that ever earned a fee: {len(total_bin_fees)}")
    print(f"sum of per-bin totals: ${grand_total:,.2f} "
          f"(candle fees: ${fees.sum():,.2f})")
    assert abs(grand_total - fees.sum()) < 1e-6

    # --- Same accumulation, weighted mode ----------------------------------
    # The pool's total fee income must not depend on how each candle's fee
    # is split among bins — only its location moves.
    weighted_totals, _ = accumulate_bin_fees(df, "weighted")
    assert set(weighted_totals) == set(total_bin_fees)
    assert abs(sum(weighted_totals.values()) - grand_total) < 1e-6
    moved = sum(abs(weighted_totals[b] - total_bin_fees[b])
                for b in total_bin_fees) / 2
    print(f"weighted mode: same {len(weighted_totals)} bins, same pool total "
          f"${sum(weighted_totals.values()):,.2f}; "
          f"${moved:,.2f} moved between bins vs equal")

    print("top 5 earning bins:")
    for bin_id in sorted(total_bin_fees, key=total_bin_fees.get, reverse=True)[:5]:
        lo, hi = get_bin_range(bin_id, BIN_STEP)
        print(f"  bin {bin_id}: ${total_bin_fees[bin_id]:,.2f}"
              f"  (UI ${raw_to_ui(lo):.2f}-{raw_to_ui(hi):.2f})")

    # --- Bar chart: total fee per bin --------------------------------------
    import matplotlib.pyplot as plt

    bin_ids = sorted(total_bin_fees)
    totals = [total_bin_fees[b] for b in bin_ids]

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.bar(bin_ids, totals, width=0.8, color="#2563eb")
    ax.set_title(
        f"Total fee earned per bin over {days:.0f} days "
        f"(step {BIN_STEP}, equal split)",
        fontsize=11, color="#3f3f46",
    )
    ax.set_xlabel("bin id (raw-price convention)", color="#52525b")
    ax.set_ylabel("total fee (USD)", color="#52525b")
    ax.tick_params(colors="#52525b", labelsize=9)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    fig.tight_layout()
    fig.savefig("data/fee_per_bin.png", dpi=150)
    print("\nchart saved to data/fee_per_bin.png")
